{% set name = "pyaml" %}
{% set version = "23.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyaml-{{ version }}.tar.gz
  sha256: eee6dde0c848e126e521e74ae2f21e7a431e4cc3d650b3338696907b237e759c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8

  run:
    - python >=3.8
    - pyyaml

test:
  imports:
    - pyaml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mk-fg/pretty-yaml
  license: WTFPL
  license_file: COPYING
  summary: PyYAML-based module to produce pretty and readable YAML-serialized data

extra:
  recipe-maintainers:
    - pmlandwehr
    - thewchan
