{% set name = "pyaml" %}
{% set version = "23.9.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyaml-{{ version }}.tar.gz
  sha256: 581ea4e99f0e308864407e04c03c609241aefa3a15dfba8964da7644baf3b217

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8

  run:
    - python >=3.8
    - pyyaml

test:
  imports:
    - pyaml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mk-fg/pretty-yaml
  license: WTFPL
  license_file: COPYING
  summary: PyYAML-based module to produce pretty and readable YAML-serialized data

extra:
  recipe-maintainers:
    - thewchan
