{% set name = "pyaml" %}
{% set version = "21.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: c6519fee13bf06e3bb3f20cacdea8eba9140385a7c2546df5dbae4887f768383

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - pip
    - python >=3.6

  run:
    - python >=3.6
    - pyyaml

test:
  imports:
    - pyaml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mk-fg/pretty-yaml
  license: WTFPL
  license_file: COPYING
  summary: PyYAML-based module to produce pretty and readable YAML-serialized data

extra:
  recipe-maintainers:
    - pmlandwehr
    - thewchan
