travis:
  secure:
    BINSTAR_TOKEN: lrZCzH/JiVJSbAUKKIPMIMlAzgOb6JrXVMHSnRcKKdK/yABqB87+l14DCYVmRrxLJyQyWiZwgZNfU1j4tpg6+ucvV0geoFBDP/nUrK7H2LPOzqGw8qnYFNJIolXQLhcmT23AV/aCqR3yYgqvaRZvDw+CF1we8VrebYpzqa3SHq5U+X3CY61wcw0lWVSFBOfx00Kc6D9Mw5E1QmnPKCw76FcXE08d5nR/eDYrjxH73KW2ght28iLROm+l59HyU7Oc8S2qsM0Es8C9sNvCD3ig4A8zRjfi0YKi4vVOnI5n1hWA5smlgOchtIVLy2ty2gHsr8957BFNmdwpc6UW6l++NWZnHaUVmFqKUBzDG/LXrqPwgnzFkSQL6PHTqOKHrvkyHF0VezqF4NChr+p/Pw06FO5a7kpsRGMjbOTdHCGZ20qNlUD2Fc4ieYMulgzwlR4TMdL4/zhu5fBw/lbaPWwLHD1CR9deBoRY/A8sPVlFLsogokx8oDo1FXHiSCsgwDppr1is1r0YdJj6CNQeaYLSLob/pNKxLlauOIFyyP8GJMRnHjsPeii2yW/aNM+akbJwS6wzG+R6uGqvF2DG8jdcwOVZdOoSja6gkSR2bpOCn5oYCvwKbP4YV10poW1qLw7qUW6Cw+BfT520LV7c/zX6IxATw61AGfcUw4ma/9h6Dh0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
